
---
- hosts: all
  become: true
  tasks:
  - name: All the package installation
    apt:
      name: [apache2, mysql-server, mysql-client, php, libapache2-mod-php, mcrypt, php-mysql, wget, unzip]
      state: present
      update_cache: yes
  - name: apache service configuration
    service:
      name: apache2
      state: started

  - name: setting up the mysql user password
    shell: "mysqladmin -u root password rootpassword && touch /var/mysqlrootsetup"
    args:
      creates: /var/mysqlrootsetup

  - name: downloading the mysql commands
    get_url:
      url: https://gitlab.com/roybhaskar9/devops/raw/master/coding/chef/chefwordpress/files/default/mysqlcommands
      dest: /tmp/mysqlcommands
    args:
      force: yes

  - name: importing mysql commands to root as rootpassword
    shell: "mysql -uroot -prootpassword < /tmp/mysqlcommands && touch /var/mysqlimportcomplete"
    args:
      creates: /var/mysqlimportcomplete

  - name: wp downloading
    get_url:
      url: https://wordpress.org/latest.zip
      dest: /tmp/latest.zip

  - name: unzip the zip file
    unarchive:
      src: /tmp/latest.zip
      dest: /var/www/html
      remote_src: yes

  - name: downloading wp-config file
    get_url:
      url: https://gitlab.com/roybhaskar9/devops/raw/master/coding/chef/chefwordpress/files/default/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php

  - name: creating file
    file:
      path: /var/www/html/wordpress
      owner: www-data
      group: www-data
      mode: 775
  - name: Restarting the apache service
    service:
      name: apache2
      state: restarted
